version: "3"

services:
  app:
    container_name: app
    
    build: .
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=secret
      - DB_NAME=data
    depends_on:
      - db
  db:
    container_name: db
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: data
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: nctuplus
      MYSQL_PASSWORD: nctuplus2023
    volumes:
      - ./backup.sql:/docker-entrypoint-initdb.d/backup.sql
    # ports:
    #   - "3306:3306"
  # nginx:
  #   image: nginx:alpine
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   ports:
  #     - "4000:80"
  #   depends_on:
  #     - app


  # backup:
  #   image: alpine
  #   volumes:
  #     - ./backups:/backups
  #     - ./backup.sh:/backup.sh
  #   environment:
  #     MYSQL_HOST: db
  #     MYSQL_USER: root
  #     MYSQL_PASSWORD: my-secret-pw
  #     MYSQL_DATABASE: mydatabase
  #   command: /bin/sh /backup.sh